name: Default

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auth with Github package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_WRITE_PACKAGES }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint