name: Publish package

on:
  push:
    branches:
      - 'main'
  release:
    types:
      - published

jobs:
  publish-github-dev:
    if: github.event_name == 'never'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@drexi'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: bash _scripts/use-dev-version.sh
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.READ_WRITE_PACKAGES}}
  publish-github-prod:
    if: github.event_name == 'never'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@drexi'

      - name: Auth with Github package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_WRITE_PACKAGES }}" > ~/.npmrc
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.READ_WRITE_PACKAGES}}
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: bash _scripts/use-prod-version.sh
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.READ_WRITE_PACKAGES}}
  publish-npm-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: |
          LATEST_GIT_COMMIT_HASH=`git log -n1 --format="%h"`
          PACKAGE_VERSION=`node -p "require('./package.json').version"`
          NPM_VERSION="$PACKAGE_VERSION-$LATEST_GIT_COMMIT_HASH"
          npm version $NPM_VERSION
          npm publish --access public
  publish-npm-prod:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: npm publish --access public --tag ${GITHUB_REF#"refs/tags/"}
